name: Deploy Site

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkboiut Sourcee
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: build

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          artifact_name: "github-pages"
